# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Rebecca Alford
tagline:          
description:      
url:              rfalford12.github.io
baseurl:          /

author:
  name:          'Rebecca Alford'
  url:            https://twitter.com/RebeccaAlford

paginate:         5

# Custom vars
version:          1.0

github:			
  repo:  

twitter:
 name:           RebeccaAlford
 url:            https://twitter.com/RebeccaAlford         
